language: r
cache: packages
dist: trusty
env:
  global:
    - MAKEFLAGS = -j2
    - ODBCSYSINI=${TRAVIS_BUILD_DIR}/travis/odbc
    - _R_CHECK_FORCE_SUGGESTS_=false

warnings_are_errors: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - unixodbc-dev

before_script:
  - export INCLUDE_DIR=/usr/include
  - export LIB_DIR=/usr/lib/x86_64-linux-gnu/
