language: r
cache: packages
env:
  global:
    - MAKEFLAGS = -j2
    - ODBCSYSINI=${TRAVIS_BUILD_DIR}/travis/odbc
    - _R_CHECK_FORCE_SUGGESTS_=false

warnings_are_errors: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - r-cran-rjava
      - unixodbc-dev

before_script:
  - export INCLUDE_DIR=/usr/include
  - export LIB_DIR=/usr/lib/x86_64-linux-gnu/

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
